[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install -g pnpm@9", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm -r build"]

[start]
cmd = "node --no-warnings=ExperimentalWarning apps/server/dist/main.js"
