[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npx --yes pnpm@10 install --frozen-lockfile"]

[phases.build]
cmds = ["npx --yes pnpm@10 -r build"]

[start]
cmd = "node --no-warnings=ExperimentalWarning apps/server/dist/main.js"
