-- Hub cloud runtime foundation.
-- This moves the hosted/readable Hub state shape to Supabase so Vercel
-- Functions can replace Railway route by route. Embeddings/vector search stay
-- intentionally out of this migration.

create extension if not exists "pgcrypto";

create table if not exists public.captures (
  id text primary key,
  source text not null,
  received_at bigint not null,
  content_hash text not null,
  raw_content_ref text not null,
  classified_domain text,
  classified_type text,
  confidence double precision,
  entities_json jsonb not null default '[]'::jsonb,
  action_items_json jsonb not null default '[]'::jsonb,
  decisions_json jsonb not null default '[]'::jsonb,
  dispatched_to_json jsonb not null default '[]'::jsonb,
  model_used text,
  status text not null default 'received',
  error_message text,
  created_at timestamptz not null default now()
);

create table if not exists public.runs (
  id text primary key,
  agent_name text not null,
  parent_run_id text,
  started_at bigint not null,
  ended_at bigint,
  model_used text not null,
  input_tokens bigint not null default 0,
  output_tokens bigint not null default 0,
  cost_usd numeric(12, 6) not null default 0,
  status text not null default 'running',
  mcp_servers_json jsonb not null default '[]'::jsonb,
  subagents_json jsonb not null default '[]'::jsonb,
  permission_tier text not null default 'R0',
  reversal_payload text,
  reversed_at bigint,
  error_message text,
  output_ref text,
  prompt_id text,
  prompt_version integer,
  target_repo text,
  run_trigger text,
  adversarial_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.briefings (
  date date primary key,
  generated_at bigint not null,
  run_id text not null,
  obsidian_ref text not null,
  rating integer,
  notes text,
  body text,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  slug text primary key,
  name text not null,
  domain text not null,
  notion_page_id text,
  linear_team_key text,
  todoist_project_id text,
  obsidian_folder text,
  status text not null default 'active',
  last_activity_at bigint,
  created_at timestamptz not null default now()
);

create table if not exists public.agent_locks (
  agent_name text primary key,
  pid integer not null,
  acquired_at bigint not null,
  lease_until bigint not null,
  holder_hostname text not null
);

create table if not exists public.feedback (
  id text primary key,
  source_type text not null check (source_type in ('ask', 'brief', 'prompt_run')),
  source_id text not null,
  signal text not null check (signal in ('acted', 'ignored', 'wrong')),
  created_at bigint not null
);

create table if not exists public.prompts (
  id text primary key,
  version integer not null default 1,
  source_sha text,
  title text not null,
  description text not null,
  body text not null,
  sensitivity text not null default 'low',
  complexity text not null default 'standard',
  inputs_schema jsonb,
  output_config jsonb not null default '{}'::jsonb,
  tags jsonb not null default '[]'::jsonb,
  synced_at bigint not null,
  enabled boolean not null default true
);

create table if not exists public.prompt_targets (
  id bigint generated by default as identity primary key,
  repo text not null,
  prompt_id text not null references public.prompts(id) on delete cascade,
  trigger text not null,
  when_expr text,
  branch text not null default 'main',
  sensitivity_override text,
  args jsonb not null default '{}'::jsonb,
  enabled boolean not null default true,
  source_sha text,
  synced_at bigint not null,
  last_run_id text,
  last_run_at bigint,
  constraint prompt_targets_repo_prompt_trigger_key unique (repo, prompt_id, trigger)
);

create table if not exists public.cron_runs (
  id uuid primary key default gen_random_uuid(),
  job_name text not null,
  status text not null check (status in ('recorded', 'running', 'success', 'error', 'local_worker_required')),
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  detail jsonb not null default '{}'::jsonb
);

create table if not exists public.webhook_events (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  delivery_id text,
  payload_hash text not null,
  capture_id text,
  status text not null check (status in ('accepted', 'duplicate', 'no_text_field', 'error')),
  payload jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

create index if not exists captures_received_at_idx on public.captures (received_at desc);
create index if not exists captures_content_hash_idx on public.captures (content_hash);
create index if not exists captures_status_idx on public.captures (status);
create index if not exists captures_source_received_idx on public.captures (source, received_at desc);

create index if not exists runs_started_at_idx on public.runs (started_at desc);
create index if not exists runs_status_idx on public.runs (status);
create index if not exists runs_agent_name_idx on public.runs (agent_name);
create index if not exists runs_prompt_started_idx on public.runs (prompt_id, started_at desc)
  where prompt_id is not null;

create index if not exists briefings_generated_at_idx on public.briefings (generated_at desc);
create index if not exists projects_status_idx on public.projects (status);
create index if not exists projects_domain_idx on public.projects (domain);
create index if not exists agent_locks_lease_until_idx on public.agent_locks (lease_until);
create index if not exists feedback_source_idx on public.feedback (source_type, source_id);
create index if not exists feedback_signal_idx on public.feedback (signal);
create index if not exists prompt_targets_trigger_idx on public.prompt_targets (trigger);
create index if not exists prompt_targets_repo_idx on public.prompt_targets (repo);
create index if not exists cron_runs_job_started_idx on public.cron_runs (job_name, started_at desc);
create index if not exists webhook_events_source_received_idx on public.webhook_events (source, received_at desc);
create unique index if not exists webhook_events_source_delivery_idx
  on public.webhook_events (source, delivery_id)
  where delivery_id is not null;
create unique index if not exists webhook_events_source_payload_hash_idx
  on public.webhook_events (source, payload_hash);

alter table public.captures enable row level security;
alter table public.runs enable row level security;
alter table public.briefings enable row level security;
alter table public.projects enable row level security;
alter table public.agent_locks enable row level security;
alter table public.feedback enable row level security;
alter table public.prompts enable row level security;
alter table public.prompt_targets enable row level security;
alter table public.cron_runs enable row level security;
alter table public.webhook_events enable row level security;

comment on table public.captures is
  'Cloud-readable Hub capture metadata and webhook capture rows. Embeddings are intentionally excluded.';
comment on table public.runs is
  'Hub agent/runtime run telemetry for Vercel status, observability, and future migration.';
comment on table public.cron_runs is
  'Vercel Cron execution log and local-worker-required records.';
comment on table public.webhook_events is
  'Idempotent webhook receipt log for Vercel-hosted webhook endpoints.';
